using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TestBase.Api.Models.Establecimientos;

namespace TestBase.Api.Migrations.Seed
{
    public static class EstablecimientoSeed
    {
        public static void SeedEstablecimientos(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Establecimiento>().HasData(
            //zona NORTE
            new Establecimiento { Id = "N01", Codigo = "N01", Nombre = "PEDRO B. PALACIOS", Domicilio = "DONATO ALVAREZ S/Nº - Cº DEL MILAGRO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N01BIS", Codigo = "N01BIS", Nombre = "NUCLEO ED. Nº 7003", Domicilio = "DONATO ALVAREZ S/Nº - Cº DEL MILAGRO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N02", Codigo = "N02", Nombre = "JARDIN INF. 3ª ETAPA", Domicilio = "J.C.SANCHEZ Y ETCHEGOYEN-Cº DEL MILAGRO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N03", Codigo = "N03", Nombre = "JARDIN INF. 4TA. ETAPA", Domicilio = "M.PRADO Y FCO CRUZ Cº DEL MILAGRO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N05", Codigo = "N05", Nombre = "RENE FAVALORO", Domicilio = "PARQUE GRAL. BELGRANO MZA. 13 - 6TA ETAPA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N06", Codigo = "N06", Nombre = "LEOPOLDO LUGONES", Domicilio = "MANZ. 334- Bº LEOPOLDO LUGONES", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N06BIS", Codigo = "N06BIS", Nombre = "NUCLEO ED. Nº 7003", Domicilio = "MANZ. 334- Bº LEOPOLDO LUGONES", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N07", Codigo = "N07", Nombre = "NICOLAS AVELLANEDA", Domicilio = "PERITO MORENO S/Nº BARRIO UNIVERSITARIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N08", Codigo = "N08", Nombre = "MONSEÑOR PEREZ ", Domicilio = "AVDA. HUSSEIN S/Nº Bº CASTAÑARES", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N08bis", Codigo = "N08bis", Nombre = "NUCLEO ED. Nº 7003", Domicilio = "AVDA. HUSSEIN S/Nº Bº CASTAÑARES", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N09", Codigo = "N09", Nombre = "EVA PERON", Domicilio = "PADRE R. ADUAGA S/Nº -GPO 298-Bº CASTAÑARES", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N10", Codigo = "N10", Nombre = "RAFAEL SOSA", Domicilio = "AVDA. PEÑALBA S/Nº -Bº J.M.CASTILLA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N10BIS", Codigo = "N10BIS", Nombre = "NUCLEO ED. Nº 7003", Domicilio = "AVDA. PEÑALBA S/Nº -Bº J.M.CASTILLA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N11", Codigo = "N11", Nombre = "PEREYRA ROSAS", Domicilio = "AVDA. BOLIVIA Y AV. YPF", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N12", Codigo = "N12", Nombre = "MIGUEL ORTIZ", Domicilio = "PJE. EL JARDIN 48 - Bº MIGUEL ORTIZ", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N12BIS", Codigo = "N12BIS", Nombre = "NUCLEO ED. Nº 7003", Domicilio = "PJE. EL JARDIN 48 - Bº MIGUEL ORTIZ", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N13", Codigo = "N13", Nombre = "JOSE VICENTE SOLA ", Domicilio = "MITRE 2000", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N13BIS", Codigo = "N13BIS", Nombre = "NUCLEO ED. Nº 7003", Domicilio = "MITRE 2000", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N14", Codigo = "N14", Nombre = "20 DE FEBRERO ", Domicilio = "AVDA. J.B. JUSTO 350 - Bº POSTAL", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N14BIS", Codigo = "N14BIS", Nombre = "NUCLEO ED. Nº 7003", Domicilio = "AVDA. J.B. JUSTO 350 - Bº POSTAL - BASE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N15", Codigo = "N15", Nombre = "BENJAMIN DAVALOS Y AVILES", Domicilio = "MANDARINOS Y LAS PALTAS Bº 3 CERRITOS", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N16", Codigo = "N16", Nombre = "JOAQUIN CASTELLANOS", Domicilio = "AVDA. REYES CATOLICOS 1580", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N17", Codigo = "N17", Nombre = "JARDIN MATERNO INF. Nº4767", Domicilio = "VICENTE LOPEZ 1560", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N18", Codigo = "N18", Nombre = "PAULA ALBARRACIN", Domicilio = "DEAN FUNES 1151 Vª BELGRANO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N19", Codigo = "N19", Nombre = "BERNARDINO RIVADAVIA", Domicilio = "25 DE MAYO 1150", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N20", Codigo = "N20", Nombre = "CORDOBA", Domicilio = "25 DE MAYO 1150", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N23", Codigo = "N23", Nombre = "ESCUELA Nº 4817-Bº JUAN PABLO II", Domicilio = "AV. EJERCITO ARG. Y RAUL GALAN Bº JUAN PABLO II", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N23BIS", Codigo = "N23BIS", Nombre = "NUCLEO ED. Nº 7003", Domicilio = "Bº JUAN PABLO II", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N25", Codigo = "N25", Nombre = "Ma. ELVIRA CASTELLANOS DE URIBURU", Domicilio = "RUTA 28 Km 11 ", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N26", Codigo = "N26", Nombre = "E.F.E.T.A.", Domicilio = "Bº EL HUAICO - AVDA DEMOCRACIA S/Nº", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "N27", Codigo = "N27", Nombre = "BICENTENARIO DE LA INDEPENDENCIA NACIONAL", Domicilio = "Bº EL HUAICO - FRANCISCO CORBALAN S/Nº", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_NORTE" },

            new Establecimiento { Id = "NI01", Codigo = "NI01", Nombre = "DIR. GRAL. DE JUSTICIA PENAL JUVENIL", Domicilio = "PERITO MORENO S/Nº - Bº UNIVERSITARIO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI02", Codigo = "NI02", Nombre = "ESC. ESP. COMISARIA  MENOR", Domicilio = "B. HUSSAIN S/Nº - Bº CASTAÑARES", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI04", Codigo = "NI04", Nombre = "AYUDAME A CRECER", Domicilio = "ZUVIRIA 752", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI05", Codigo = "NI05", Nombre = "CPO.  POLICIA INF. COM. 6TA.", Domicilio = "TNE. MAYOL S/Nº CIUDAD DEL MILAGRO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI06", Codigo = "NI06", Nombre = "CASITA DE BELEN", Domicilio = "LOS AZAHARES 63 - Bº TRES CERRITOS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI09", Codigo = "NI09", Nombre = "SUBCOMISARIA CASTAÑARES", Domicilio = "JAIME DURAND Y PERITO MORENO Bº UNIVERSITARIO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI13", Codigo = "NI13", Nombre = "ESCUELA DE FUTBOL SUPER BOYS", Domicilio = "LOS MIRASOLES 486 B - CASA 10 -", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI22", Codigo = "NI22", Nombre = "CLUB ABUELOS ANGEL DE LA GUARDA", Domicilio = "PJE. ALFONSO PERALTA 425 - Bº MIGUEL ORTIZ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI23", Codigo = "NI23", Nombre = "C.I.C Bº UNION", Domicilio = "MANZ. 357 A- LOTE - Bº UNION", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI24", Codigo = "NI24", Nombre = "FUNDACION ANPÙY", Domicilio = "Bº P.GRAL BELGRANO - ETAPA 3 - AVDA JAIME DURAN", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI28", Codigo = "NI28", Nombre = "MERENDERO FUNDACION SALTA CRECER", Domicilio = "MANZ J LOTE 15 Bº 15 DE SETIEMBRE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI29", Codigo = "NI29", Nombre = "CLUB ABUELOS SONRISAS DE OTOÑO", Domicilio = "MANZ. 421C LOTE 1 -Bº 17 DE OCTUBRE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI30", Codigo = "NI30", Nombre = "ASOC. TRABAJ. DE LA SANIDAD ARG.", Domicilio = "AVDA.SANANTONIO DE LOS COBRES  4 -Bº CASTAÑARES", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI32", Codigo = "NI32", Nombre = "ANEXO ABORDAJE EN DROGAS", Domicilio = "LUIS AGOTE Y PERITO MORENO-MANZ.235B LOTE 8 -Bº UNIV.", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI33", Codigo = "NI33", Nombre = "VICARIA NTRA SRA DE LOURDES", Domicilio = "MANZ. 350 - Bº JUAN PABLO II", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI34", Codigo = "NI34", Nombre = "MERENDERO EL ARCA DE NOE", Domicilio = "MANZ. 327C - LOTE 17 - BARRIO 1RO. DE MAYO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI38", Codigo = "NI38", Nombre = "ANEXO ESC. DE MUSICA MOV. INT. VEC.", Domicilio = "B° PARQ. GRAL BELR. ETAPA 4-MAN 1-DUPLEX 1-SRA. VIOLETA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI42", Codigo = "NI42", Nombre = "MERENDERO PANCITAS FELICES", Domicilio = "ZUVIRIA 2076 ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI43", Codigo = "NI43", Nombre = "CUERPO INFANTIL COM. Nº 103", Domicilio = "MANZ. 356A LOTE 6 Bº UNION", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI44", Codigo = "NI44", Nombre = "CUERPO INFANTIL COM. Nº 103", Domicilio = "LAGUNA BLANCA MNA. 388A-LOTE24 Bº 17 DE OCTUBRE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI45", Codigo = "NI45", Nombre = "PREJARDIN DIVINO NIÑO", Domicilio = "AV. ARENALES 2500 - Bº MILITAR.", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI46", Codigo = "NI46", Nombre = "S.E.R.", Domicilio = "LOS OMBUES 392 - Bº TRES CERITOS - SRA RAQUEL", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI47", Codigo = "NI47", Nombre = "CUERPO INF. COM 3ra", Domicilio = "COMPL DEP B°M. ORTIZ ZUVIRIA N°2750", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI49", Codigo = "NI49", Nombre = "MERENDERO AMANDITA", Domicilio = "MANZ. 403 - B lote 6 Bº 17 DE OCTUBRE- TEL.256886", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NI52", Codigo = "NI52", Nombre = "MERENDERO PARRQ DE LA RESURRECCION", Domicilio = "RUTA 9 KM 1610", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_NORTE" },

            new Establecimiento { Id = "NS01", Codigo = "NS01", Nombre = "COLEGIO SECUNDARIO C. DEL MILAGRO", Domicilio = "FRAGATA SARMIENTO S/Nº - Bº CIUDAD DEL MILAGRO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS02", Codigo = "NS02", Nombre = "BACHILLERATO PROF. AMADEO SIROLLI", Domicilio = "25 DE MAYO 1150", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS03", Codigo = "NS03", Nombre = "COLEGIO Nº 5048 - JUANA MANUELA GORRITI", Domicilio = "CHULUPIES Y ARAUCANOS - Bº Pº BELGRANO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS04", Codigo = "NS04", Nombre = "COLEGIO BATALLA DE SALTA", Domicilio = "Bº UNIVERSITARIO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS05", Codigo = "NS05", Nombre = "COLEGIO SECUNDARIO REYES CATOLICOS", Domicilio = "LAS ROSAS  253", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS06", Codigo = "NS06", Nombre = "COLEGIO SALVADOR MAZZA", Domicilio = "LOS PIQUILLINES 450", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS07", Codigo = "NS07", Nombre = "ESCUELA DE COMERCIO 5075", Domicilio = "AVDA. DEMOCRACIA S/Nº - Bº EL HUAYCO II", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS08", Codigo = "NS08", Nombre = "ANEXO FRAY MAMERTO ESQUIU", Domicilio = "ALCAIDIA GRAL-COMPLEJO CDAD. JUDICIAL", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS09", Codigo = "NS09", Nombre = "BACHILLERATO TOMAS CABRERA", Domicilio = "AVDA. DEMOCRACIA S/Nº - Bº EL HUAYCO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },
            new Establecimiento { Id = "NS10", Codigo = "NS10", Nombre = "COLEGIO SAN JOSE", Domicilio = "PERITO MORENO 256 Bº UNIVERSITARIO TEL 4251259", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_NORTE" },

            new Establecimiento { Id = "NT01", Codigo = "NT01", Nombre = "ESCUELA DE ED. TECNICA Nº 3141", Domicilio = "CAPITAN PAIVA ESQ CORONEL QUESADA - Cº DEL MILAGRO", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_NORTE" },

            //zona SUR
            new Establecimiento { Id = "S01", Codigo = "S01", Nombre = "25 DE MAYO DE 1810", Domicilio = "FCO. ARIAS 824 - Vª SOLEDAD", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S02", Codigo = "S02", Nombre = "BRIG. ALVAREZ Y ARENALES", Domicilio = "LOS LANCEROS E INDEPENDENCIA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S03", Codigo = "S03", Nombre = "REINO DE BELGICA", Domicilio = "ITUZAINGO 1012 Vº SAN ANTONIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S04", Codigo = "S04", Nombre = "ALEJANDRO GAUFFIN", Domicilio = "MAR TIRRENO 1145 - Bº SAN REMO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S05", Codigo = "S05", Nombre = "REPUBLICA ARGENTINA", Domicilio = "REP. DEL LIBANO 850 - Bº CASINO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S07", Codigo = "S07", Nombre = "9 DE JULIO", Domicilio = "DR. URIBURU ESQ. M. LEZAMA - VILLA MARIA ESTER", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S07BIS", Codigo = "S07BIS", Nombre = "ANEXO NUCLEO ED. Nº 7004", Domicilio = "DR.URIBURU ESQ. M. LEZAMA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S09", Codigo = "S09", Nombre = "JARDIN INF. Vª ESTELA", Domicilio = "FCO. ARIAS Y LEZCANO VILLA ESTELA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S10", Codigo = "S10", Nombre = "RAUL GOYTEA", Domicilio = "LIBERTAD Y MANUELA G. DE TODD -Bº MUNICIPAL", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S11", Codigo = "S11", Nombre = "PCIA. DE BS.AS.", Domicilio = "FCO. LOPEZ 1630- Vª MARIA ESTHER", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S12", Codigo = "S12", Nombre = "MIGUEL DE C. SAAVEDRA", Domicilio = "RIO MEDINA Y RIO SAN CARLOS Nº 590 - Vª LAVALLE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S12BISA", Codigo = "S12BISA", Nombre = "NUCLEO ED. Nº 7006", Domicilio = "RIO MEDINA Y RIO SAN CARLOS Nº 590 - Vª LAVALLE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S12BIS B", Codigo = "S12BIS B", Nombre = "ANEXO NUCLEO ED. 7006", Domicilio = "CARLOS OUTES 260 Vº LAVALLE-GUARDERIA JUAN GALO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S12BIS C", Codigo = "S12BIS C", Nombre = "ANEXO NUCLEO ED. 7006", Domicilio = "RIO PIEDRAS Nº 280 - COL. AMERICA LATINA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S13", Codigo = "S13", Nombre = "DELFIN LEGUIZAMON", Domicilio = "PJE. FELIPE VALLESE S/Nº - BOULOGNE SUR MER", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S13BIS", Codigo = "S13BIS", Nombre = "ANEXO NUCLEO ED. Nº 7006", Domicilio = "PJE. FELIPE VALLESE S/Nº - BOULOGNE SUR MER", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S14", Codigo = "S14", Nombre = "PCIA. DE SALTA", Domicilio = "ANDRES CHAZARRETA 436- Bº STA CECILIA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S14BIS", Codigo = "S14BIS", Nombre = "ANEXO NUCLEO ED. Nº 7006", Domicilio = "MANZ. 252 L - Bº SAN FCO. SOLANO-TEC 3118", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S15", Codigo = "S15", Nombre = "INDEPENDENCIA NACIONAL", Domicilio = "MANSILLA S/Nº - Bº JUAN CALCHAQUI", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S16", Codigo = "S16", Nombre = "MA. REYES DE CAMPOS", Domicilio = "RUTA 26 - FINCA VELARDE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S17", Codigo = "S17", Nombre = "CRISTOBAL COLON ", Domicilio = "PJE. FELIPE VALLESE S/Nº - BOULOGNE SUR MER", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S18", Codigo = "S18", Nombre = "RICARDO DURAND", Domicilio = "MANZ. 4 - BARRIO SAN IGNACIO 674", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S18 BIS", Codigo = "S18 BIS", Nombre = "ANEXO NUCLEO ED. 7006", Domicilio = "MANZ. 4 - BARRIO SAN IGNACIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S20", Codigo = "S20", Nombre = "CTRO. ED. FE Y ALEGRIA BLANCA", Domicilio = "MANZ. 465 A - Bº SOLIDARIDAD 2DA. ETAPA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S22", Codigo = "S22", Nombre = "MARIANO MORENO", Domicilio = "AVDA. ROBERTO ROMERO S/Nº - Bº EL TRIBUNO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S22BIS", Codigo = "S22BIS", Nombre = "ANEXO NUCLEO ED. 7006", Domicilio = "AVDA. ROBERTO ROMERO S/Nº - Bº EL TRIBUNO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S23", Codigo = "S23", Nombre = "MARIQUITA SANCHEZ DE THOMPSON", Domicilio = "PATAGONIA ARGENTINA 2950- Bº INTERSINDICAL", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S24", Codigo = "S24", Nombre = "CLARA  SARAVIA LINARES DE ARIAS", Domicilio = "LRA RADIO NACIONAL Nº3495 - Bº INTERSINDICAL ", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S25", Codigo = "S25", Nombre = "MARIA DEL Rº DE SAN NICOLAS", Domicilio = "LAS GOLONDRINAS Y LOS HORNEROS-BANCARIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S26", Codigo = "S26", Nombre = "RAUL CORTAZAR", Domicilio = "LOS HORNEROS 4420 - Bº BANCARIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S27", Codigo = "S27", Nombre = "IV CENT. FUND. DE SALTA", Domicilio = "AVDA PERU - PJE 12 - Bº SANTA ANA I", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S27BIS", Codigo = "S27BIS", Nombre = "ANEXO NUCLEO ED. Nº 7006", Domicilio = "AVDA PERU - PJE 12 - Bº SANTA ANA I", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S28", Codigo = "S28", Nombre = "CESAR FERMIN PERDIGUERO", Domicilio = "PJE 21 - ALT. 1400 - Bº SANTA ANA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S29", Codigo = "S29", Nombre = "MARCOS SASTRE", Domicilio = "RUTA 68 - RIO ANCHO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S30", Codigo = "S30", Nombre = "SUBMARINO ARA", Domicilio = "RUTA 51 KM. 842 - SAN LUIS", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S31", Codigo = "S31", Nombre = "LEGADO GRAL BELGRANO", Domicilio = "AVDA. RALLE S/Nº - Bº LIMACHE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S32", Codigo = "S32", Nombre = "RUDECINDO ALVARADO", Domicilio = "FELIPE SOLA S/Nº - VILLA ESMERALDA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S33", Codigo = "S33", Nombre = "NTRA. SRA. DEL MILAGRO", Domicilio = "IVONE RETAMOZO DE IÑIGUEZ S/Nº E-11-Bº LIMACHE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S34", Codigo = "S34", Nombre = "Bº SAN CARLOS", Domicilio = "MANZ. 51 Bº SAN CARLOS", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S35", Codigo = "S35", Nombre = "ROQUE CHIELLI", Domicilio = "GABRIEL GUEMES 243 - Bº DON EMILIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S41", Codigo = "S41", Nombre = "GUARDERIA MONSEÑOR PÈREZ", Domicilio = "ANSELMO ROJO Nº 51 -Bº MUNICIPAL", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S42", Codigo = "S42", Nombre = "ESC. GRAL JUAN JOSE VALLE", Domicilio = "Bº LIBERTAD MZA 391  B ", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S42BIS", Codigo = "S42BIS", Nombre = "ANEXO NUCLEO ED. 7006", Domicilio = "Bº LIBERTAD MZA 391  B ", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S43", Codigo = "S43", Nombre = "ESC. ELSA SALFITTY ", Domicilio = "AVDA DIAZ VILLALBA S/Nº MZA 355A-B Bº SIGLO XXI", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S43BIS", Codigo = "S43BIS", Nombre = "ANEXO NUCLEO ED. 7006", Domicilio = "AVDA DIAZ VILLALBA S/Nº", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S46", Codigo = "S46", Nombre = "ESCUELA Nº 4811- 2 DE MAYO CRUCERO A.R.A GRAL. BELGRANO", Domicilio = "MZA 438 A-3RA ETAPA- B° SOLIDARIDAD", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S46BIS", Codigo = "S46BIS", Nombre = "ANEXO NUCLEO ED. 7006", Domicilio = "Bº SOLIDARIDAD 4TA. ETAPA- FRENTE AL C.I.C.", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S47", Codigo = "S47", Nombre = "ESCUELA BICENTENARIO BATALLA SALTA", Domicilio = "LUCIO MANSILLA Y SANTILLAN -Bº DEMOCRACIA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "S47BIS", Codigo = "S47BIS", Nombre = "ANEXO NUCLEO ED. 7006", Domicilio = "LUCIO MANSILLA Y SANTILLAN -Bº DEMOCRACIA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_SUR" },

            new Establecimiento { Id = "SI05", Codigo = "SI05", Nombre = "SALON USOS M. SAN BENITO", Domicilio = "MANZ. 317- LOTE B- Bº SAN BENITO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI13", Codigo = "SI13", Nombre = "FUNDACION DESARROLLO 2000", Domicilio = "REPUBLICA DE SIRIA 611", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI22", Codigo = "SI22", Nombre = "S.P.E.S.", Domicilio = "PJE. 23 CASA 1553-ESQUINA-B° SANTA ANA 1- SRA. LUCIA CASTRO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI28", Codigo = "SI28", Nombre = "SUBCOMISARIA DE SAN LUIS", Domicilio = "RUTA 51 - SAN LUIS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI29", Codigo = "SI29", Nombre = "PARROQUIA ENCARNACION DEL VERBO", Domicilio = "etapa 6 manz. 2 - Casa 5 - Flia Liendro", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI31", Codigo = "SI31", Nombre = "CPO. INF. COM. EL TRIBUNO", Domicilio = "LA RAZON Y LOS ANDES Bº EL TRIBUNO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI33", Codigo = "SI33", Nombre = "POL. INF. COM. 12 - Bº STA. ANA 1", Domicilio = "DEST. COMISARIA Nº 12- Bº STA. ANA 1", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI34", Codigo = "SI34", Nombre = "HOGAR DE CIEGOS HABID YAZLLE", Domicilio = "LERMA 1445", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI37", Codigo = "SI37", Nombre = "MERENDERO NIÑO JESUS DE PRAGA", Domicilio = "MANZ. 514 D - LOTE 13 - Bº 1RA. JUNTA- 155120711", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI39", Codigo = "SI39", Nombre = "FUNDACION CHANGUITO DIOS", Domicilio = "ESTEBAN ECHEVERRIA S/Nº Bº JUAN CALCHAQUI", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI44", Codigo = "SI44", Nombre = "ESC. DE POL. INF. DE TRANSITO", Domicilio = "ESTANISLAO  LOPEZ 191 - FINCA INDEPENDENCIA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI56", Codigo = "SI56", Nombre = "C.I.C. BARRIO SANTA CECILIA", Domicilio = "BARRIO SANTA CECILIA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI57", Codigo = "SI57", Nombre = "MERENDERO MERA FIGUEROA", Domicilio = "MANZ.25 LOTE 16 - BARRIO LA PAZ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI58", Codigo = "SI58", Nombre = "ESC. MUNICIPAL DE BOX -Bº NORTE GRANDE", Domicilio = "MANZ. 202 LOTE 7 Bº NORTE GRANDE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI60", Codigo = "SI60", Nombre = "CAT. PARROQUIA STELLA MARIS", Domicilio = "manz. K - casa 4 - bº circulo 1", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI61", Codigo = "SI61", Nombre = "MERENDERO FERNANDO SUÑER", Domicilio = "CARLOS OUTE 341 Vº LAVALLE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI64", Codigo = "SI64", Nombre = "PARROQUIA MARIA REINA ", Domicilio = "LA RAZON 4001- Bº EL TRIBUNO 4240900", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI65", Codigo = "SI65", Nombre = "PREJARDIN DIVINO NIÑO-PARR.MA. REINA", Domicilio = "AVDA. FELIPE VARELA  ESQ. A. MEDINA-Bº SAN FCO. SOL", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI68", Codigo = "SI68", Nombre = "GUARDERIA SANTA TERESA DE JESUS", Domicilio = "AVDA. DR. ERNESTO GUEVARA - VILLA SAN ANTONIO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI70", Codigo = "SI70", Nombre = "CPO. INF. COM. 15", Domicilio = "MAR MEDITERRANEO 223- Bº SAN REMO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI72", Codigo = "SI72", Nombre = "MERENDERO BARRIO MUNICIPAL", Domicilio = "MANUELA G. DE TODD Nº 1600", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI75", Codigo = "SI75", Nombre = "MOV. DE INTEGRACION VECINAL", Domicilio = "MANZ. Q.CASA Nº 5 - Bº STA. CECILIA ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI76", Codigo = "SI76", Nombre = "FUND.EMPRENDEDORES FOR.EM.ES", Domicilio = "Bº LIMACHE - ETAPA 10 - MANZ 3 - CASA 3", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI78", Codigo = "SI78", Nombre = "MERENDERO LA NUEVA ILUSION", Domicilio = "PJE. LOS INFERNALES 1526 - Vª SAN ANTONIO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI79", Codigo = "SI79", Nombre = "COMEDOR PADRE SALUSTIANO", Domicilio = "FLORIDA 1548", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI80", Codigo = "SI80", Nombre = "MERENDERO FUNDACION DULCE SOL", Domicilio = "PJE DEL MILAGRO 1581 Bº MUNICIPAL", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI81", Codigo = "SI81", Nombre = "VICARIA NTRA.SRA.Rº SAN NICOLAS", Domicilio = "CORDOBA 1810 - Bº CEFERINO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI86", Codigo = "SI86", Nombre = "SUBCOMISARIA Bº LIMACHE", Domicilio = "AVDA RALLE ESQ CABO PRIMERA CISTERNA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI87", Codigo = "SI87", Nombre = "CENTRO SAN MARTIN DE PORRES", Domicilio = "MANZ. 449 A - LOTE 11 - 3RA ETAPA Bº SOLIDAR.", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI88", Codigo = "SI88", Nombre = "ESC.FUTBOL POR SIEMPRE UNIDOS", Domicilio = "ARTURO DAVALOS 71 - Vº SOLEDAD / Pan pasa a buscar de planta", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI89", Codigo = "SI89", Nombre = "GUARDERIA MUNICIPAL EL NIÑO FELIZ", Domicilio = "JOAQUIN CASTELLENOS 999", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI90", Codigo = "SI90", Nombre = "MERENDERO Bº FRATERNIDAD", Domicilio = "MANZ. 337B - LOTE 37 - Bº FRATERNIDAD", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI94", Codigo = "SI94", Nombre = "CENTRO DE ABUELOS MARIA DEL ROSARIO", Domicilio = "ETAPA 4 - MANZ. 1 - CASA 7- Bº LIMACHE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI95", Codigo = "SI95", Nombre = "MERENDERO CEFERINO FUTBOL CLUB", Domicilio = "VICARIO ZAMBRANO Nº66 - Bº. CEFERINO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI96", Codigo = "SI96", Nombre = "MERENDERO PANCITAS FELICES-Bº DEMOCRACIA", Domicilio = "MANZ. 368 B - LOTE 14 - Bº DEMOCRACIA (EXMANZ.17- LOTE 9)", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI97", Codigo = "SI97", Nombre = "CUERPO INFANTIL COM. 10º", Domicilio = "AVDA. FELIPE VARELA 500 Bº SANTA CECILIA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI98", Codigo = "SI98", Nombre = "CUERPO INFANTIL COM. Bº SAN IGNACIO", Domicilio = "DESTACAMENTO POL. Bº SAN IGNACIO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI99", Codigo = "SI99", Nombre = "CUERPO INF. COM. 17 - Bº SOLIDARIDAD - 4TA. ETAPA", Domicilio = "DESTACAMENTO POLICIA Bº SOLIDARIDAD 4TA. ETAPA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI100", Codigo = "SI100", Nombre = "MERENDERO FUNDACION LLANKAY", Domicilio = "MNA 302B Bº JUAN CALCHAQUI", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI102", Codigo = "SI102", Nombre = "MERENDERO Bº 23 DE AGOSTO", Domicilio = "MANZ. E CASA13 - Bº 23 DE AGOSTO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI106", Codigo = "SI106", Nombre = "C.I.C. CARLOS XAMENA", Domicilio = "MNA.414B-ETAPA 4 - Bº SOLIDARIDAD", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI111", Codigo = "SI111", Nombre = "PREJARDIN MARTINA TESI", Domicilio = "MANZ. 1 - LOTE D - Bº CONVIVENCIA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI112", Codigo = "SI112", Nombre = "FUNDACION CORAZON Y ESFUERZO", Domicilio = "MANZ. 36 CASA 30 - BARRIO SAN IGNACIO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI113", Codigo = "SI113", Nombre = "MEREND. CTRO. MISIONERO DIVINA MISERICORDIA", Domicilio = "AVDA. FELIPE VARELA 1421 FLIA ESTRADA YLLESCA BºNORTE GRANDE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI114", Codigo = "SI114", Nombre = "ESCUELA DE FUTBOL FINCA VALDIVIA", Domicilio = "MANZ. 618 A - CASA 11 - FINCA VALDIVIA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI115", Codigo = "SI115", Nombre = "MERENDERO MADRES UNIDAS", Domicilio = "MANZ. 321 A - CASA11 - BARRIO SAN BENITO-4385411", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI116", Codigo = "SI116", Nombre = "MERENDERO JESUS PAN DE VIDA", Domicilio = "MANZ F LOTE 9 Bº JUSTICIA CEL 156844629", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI117", Codigo = "SI117", Nombre = "CUERPO INF. POL. ECOLOGICA ", Domicilio = "SAN FELIPE Y SANTIAGO 2100 Vº MARIA ESTHER", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI122", Codigo = "SI122", Nombre = "MERENDERO ANGELITOS DE LA PAZ", Domicilio = "435 C- BARRIO LA PAZ-SUM-SRA. FABIOLA -CEL 155054130", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI124", Codigo = "SI124", Nombre = "MERENDERO SUEÑOS DE NIÑOS", Domicilio = "MANZ.252 B - LOTE 22 - Bº SAN FRANCISCO SOLANO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI125", Codigo = "SI125", Nombre = "CUERPO INF.COM.Vª PALACIOS", Domicilio = "DESTACAMENTO VILLA PALACIOS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI130", Codigo = "SI130", Nombre = "MEREN.MARCELINO PAN Y VINO", Domicilio = "MANZANA 508 B LOTE 8 BARRIO PRIMERA JUNTA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI131", Codigo = "SI131", Nombre = "BSPA", Domicilio = "PJE. FELIPE VALLESE S/Nº - BOULOGNE SUR MER", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI132", Codigo = "SI132", Nombre = "MERENDERO NTRA SRA DE URKUPIÑA", Domicilio = "MNA 471D CASA 21 Bº LOS LAPACHOS ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI133", Codigo = "SI133", Nombre = "CDI. MONSEÑOR ENRIQUE ANGELELLI", Domicilio = "MNA 316 LOTE 1 Bº SAN BENITO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI134", Codigo = "SI134", Nombre = "ESC. DE BOX BOULOGNE SUR MER", Domicilio = "JOAQUIN V. GONZALEZ 488 - Bº BOULOGNE SUR MER", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SI135", Codigo = "SI135", Nombre = "ESC. DE BOX AMILCAR BRUSA", Domicilio = "MZA 447 B LOTE 13 3ra ETAPA Bº SOLIDARIDAD ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_SUR" },

            new Establecimiento { Id = "SS01", Codigo = "SS01", Nombre = "COLEGIO 2 DE ABRIL 1982", Domicilio = "FCO. ARIAS Y ANSELMO ROJO. ", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS02", Codigo = "SS02", Nombre = "COLEGIO SECUNDARIO GRAL JOSE DE SAN MARTIN", Domicilio = "AVDA. REPUBLICA DEL LIBANO S/N - BARRIO CASINO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS02B", Codigo = "SS02B", Nombre = "COLEGIO SECUNDARIO  GRAL JOSE DE SAN MARTIN", Domicilio = "LOS LANCEROS E INDEPENDENCIA", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS03", Codigo = "SS03", Nombre = "ESCUELA DE COMERCIO DR. ERNESTO ARAOZ", Domicilio = "RADIO ESQUEL DE CHUBUT - BARRIO INTERSINDICAL", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS04", Codigo = "SS04", Nombre = "COLEGIO SECUNDARIO AMERICA LATINA", Domicilio = "RIO PIEDRAS Nº 280", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS06", Codigo = "SS06", Nombre = "COLEGIO JUAN PABLO II", Domicilio = "ITUZAINGO 1002", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS08", Codigo = "SS08", Nombre = "COLEGIO JUAN CARLOS SARAVIA", Domicilio = "AVDA. RALLE Y VICTOR H. JUAREZ - BARRIO LIMACHE", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS09", Codigo = "SS09", Nombre = "COLEGIO  JUAN CARLOS SARAVIA - ANEXO-", Domicilio = "AVDA. RALLE Y VICTOR H. JUAREZ - BARRIO LIMACHE", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS10", Codigo = "SS10", Nombre = "ESCUELA DE COMERCIO DR. RENE FAVALORO", Domicilio = "AVDA. DEL TRABAJO S/Nº - VILLA PALACIOS", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS11", Codigo = "SS11", Nombre = "COLEGIO SECUNDARIO SIGLO XXI", Domicilio = "AVDA. DIAZ VILLALBA S/Nº", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS12", Codigo = "SS12", Nombre = "COLEGIO WALTER ADET", Domicilio = "AVDA. RICARDO BALBIN Nº 900", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS13", Codigo = "SS13", Nombre = "COLEGIO SECUNDARIO VILLA ESMERALDA", Domicilio = "FELIPE SOLA S/Nº - VILLA ESMERALDA", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS14", Codigo = "SS14", Nombre = "CENTRO ED. FE Y ALEGRIA AMARILLA", Domicilio = "MANZ. 417 A BARRIO SOLIDARIDAD - 3RA. ETAPA", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "SS15", Codigo = "SS15", Nombre = "RAUL  GOYTIA", Domicilio = "LIBERTAD ESQ. MANUELA G. DE TOOD", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_SUR" },

            new Establecimiento { Id = "ST01", Codigo = "ST01", Nombre = "MAESTRO DANIEL O. REYES N° 3117", Domicilio = "MAR BLANCO 350 - BARRIO SAN REMO", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "ST02", Codigo = "ST02", Nombre = "ESCUELA Nº 3118", Domicilio = "MANZ. 252 L - BARRIO SAN FCO. SOLANO", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_SUR" },
            new Establecimiento { Id = "ST03", Codigo = "ST03", Nombre = "ESCUELA GRAL MARTIN MIGUEL DE GUEMES ", Domicilio = "RUTA AVDA KENEDY", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_SUR" },

            //zona CENTRO
            new Establecimiento { Id = "C01", Codigo = "C01", Nombre = "JULIO A. ROCA", Domicilio = "BUENOS AIRES  750", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C02", Codigo = "C02", Nombre = "MARIANO CASTEX", Domicilio = "SAN JUAN 619", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C04", Codigo = "C04", Nombre = "JUANA AZURDUY DE PADILLA", Domicilio = "SANTA FE 875", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C04BIS", Codigo = "C04BIS", Nombre = "ANEXO NUCLEO ED. Nº 7004", Domicilio = "SANTA FE 875", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C06", Codigo = "C06", Nombre = "ESCUELA Nº 7.001  PRIMARIA P/JOVENES", Domicilio = "25 DE MAYO PRIMERA CUADRA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C07", Codigo = "C07", Nombre = "ZORRILLA - 20 DE FEBRERO", Domicilio = "INGRESO 25 DE MAYO PRIMERA CUADRA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C08", Codigo = "C08", Nombre = "DOMINGO FAUSTINO SARMIENTO", Domicilio = "ALVARADO 427", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C10", Codigo = "C10", Nombre = "JUAN B. ALBERDI", Domicilio = "CASEROS 1150", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C11", Codigo = "C11", Nombre = "MARTIN M. DE GUEMES", Domicilio = "BELGRANO 666", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C12", Codigo = "C12", Nombre = "GRAL MANUEL BELGRANO - PRIMARIA", Domicilio = "MITRE 767", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C13", Codigo = "C13", Nombre = "GRAL MANUEL BELGRANO -NIVEL INICIAL", Domicilio = "BALCARCE 764", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C14", Codigo = "C14", Nombre = "JUSTO JOSE DE URQUIZA", Domicilio = "ZUVIRIA 290", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C15", Codigo = "C15", Nombre = "JACOBA SARAVIA", Domicilio = "DEAN FUNES 750", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C17", Codigo = "C17", Nombre = "GRAL. JOSE DE SAN MARTIN", Domicilio = "AMEGHINO 520", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C18", Codigo = "C18", Nombre = "EDUCACION INTERMEDIA", Domicilio = "MENDOZA 315", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C23", Codigo = "C23", Nombre = "INDALECIO GOMEZ", Domicilio = "AV. BICENT. BATALLA DE SALTA 160", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C25", Codigo = "C25", Nombre = "JOSE EVARISTO URIBURU", Domicilio = "VICENTE LOPEZ 38- EDIF. COL. F.ZUVIRIA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "C26", Codigo = "C26", Nombre = "ANEXO NUCLEO ED. 7006 CTRO DE DIA ", Domicilio = "BELGRANO 447 - 4227622 SRA. MARTA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_CENTRO" },

            new Establecimiento { Id = "CI01", Codigo = "CI01", Nombre = "HOGAR CRISTO REY", Domicilio = "CATAMARCA 718 ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI02", Codigo = "CI02", Nombre = "HOGAR SAN VTE. DE PAUL", Domicilio = "CASEROS 108", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI03", Codigo = "CI03", Nombre = "ALBERGUE COOPERADORA ASISTENCIAL", Domicilio = "ALVARADO 116", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI04", Codigo = "CI04", Nombre = "C.R.I.O.S.", Domicilio = "TUCUMAN 667", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI05", Codigo = "CI05", Nombre = "I.E.F.E.L.", Domicilio = "VICARIO TOSCANO 48 - VILLA SOLEDAD", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI06", Codigo = "CI06", Nombre = "A.D.A.N.A.", Domicilio = "MARTIN CORNEJO 98", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI07", Codigo = "CI07", Nombre = "DIRECCION DE DISCAPACIDAD", Domicilio = "CASEROS 1737", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI08", Codigo = "CI08", Nombre = "ONG TODO PARA TODOS", Domicilio = "ALSINA 450", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI10", Codigo = "CI10", Nombre = "ASOC. SAN ANTONIO DE PADUA", Domicilio = "JOAQUIN CASTELLANOS 650", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI12", Codigo = "CI12", Nombre = "I.N.P.R.E.D.", Domicilio = "florida 880", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI13", Codigo = "CI13", Nombre = "SOCIEDAD DE LA ESTRELLA", Domicilio = "JUJUY 835", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI14", Codigo = "CI14", Nombre = "CENTRO ORTODOXO DE SALTA", Domicilio = "PELLEGRINI 250", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI15", Codigo = "CI15", Nombre = "BATALLON Nº 9 - M.M. GUEMES", Domicilio = "CASEROS 1250", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI16", Codigo = "CI16", Nombre = "CENTRO TERAPEUTICO ANIDAR", Domicilio = "BALCARCE 380 Y J.M. LEGUIZAMON", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI17", Codigo = "CI17", Nombre = "IGLESIA BUENAS NUEVAS", Domicilio = "ESPAÑA 1550", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI19", Codigo = "CI19", Nombre = "PARROQUIA SAN ALFONSO ", Domicilio = "25 DE MAYO 580 - PORTERIA COLEGIO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI21", Codigo = "CI21", Nombre = "FUNDACION SALTEÑA DE CIEGOS", Domicilio = "SAN LUIS 491", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI22", Codigo = "CI22", Nombre = "FUNDACION REVIVIR", Domicilio = "PELLEGRINI 56", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI23", Codigo = "CI23", Nombre = "CTRO. TERAPEUTICO CRECIENDO", Domicilio = "ESPAÑA 820", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI25", Codigo = "CI25", Nombre = "SUBSECRETARIA DE PUEBLOS ORIGINARIOS", Domicilio = "PELLEGRINI 44", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI26", Codigo = "CI26", Nombre = "UNIVERSIDAD ABIERTA DE LA 3RA EDAD", Domicilio = "MITRE Nº 383 TEL 4314024", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI27", Codigo = "CI27", Nombre = "CENTRO JUVENTUD ANTONIANA", Domicilio = "LERMA 649", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI27B", Codigo = "CI27B", Nombre = "CENTRO JUVENTUD ANTONIANA-NIÑOS ESP.", Domicilio = "LERMA 649-CEL 154586655 - SR. MOYA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI29", Codigo = "CI29", Nombre = "ESC.DE FUT B° AUTODROMO-SR.TISSERA", Domicilio = "pasa a buscar por planta proveedora", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI30", Codigo = "CI30", Nombre = "CLUB ATLETICO INDEPENDIENTE", Domicilio = "LAVALLE 760", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CI31", Codigo = "CI31", Nombre = "FUNDACION ESPACIOS", Domicilio = "ZUVIRIA Nº 552 154456419", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_CENTRO" },

            new Establecimiento { Id = "CS01", Codigo = "CS01", Nombre = "ESCUELA DE COMERCIO HIPOLITO IRIGOYEN", Domicilio = "GRAL. MITRE Nº 468", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS02", Codigo = "CS02", Nombre = "COLEGIO 20 DE FEBRERO", Domicilio = "CASEROS Nª 1866", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS03", Codigo = "CS03", Nombre = "ESCUELA DE COMERCIO Nº 5047-B. ZORRILLA", Domicilio = "MITRE 349", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS04", Codigo = "CS04", Nombre = "COLEGIO DR. ARTURO ILLIA", Domicilio = "MITRE Nº 468", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS05", Codigo = "CS05", Nombre = "COLEGIO MANUEL CASTRO", Domicilio = "PASEO GUEMES  Nº 51", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS06", Codigo = "CS06", Nombre = "COLEGIO ADOLFO GUEMES Nº 5082", Domicilio = "PASEO GUEMES  Nº 51", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS07", Codigo = "CS07", Nombre = "ESCUELA DE COMERCIO VICTORINO DE LA PLAZA", Domicilio = "LEGUIZAMON Nº 129", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS08", Codigo = "CS08", Nombre = "COLEGIO CENTRO POLIVALENTE DE ARTE", Domicilio = "BELGRANO 474", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS08BIS", Codigo = "CS08BIS", Nombre = "COLEGIO CENTRO POLIVALENTE DE ARTE- ANEXO", Domicilio = "ITUZAINGO 371", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS10", Codigo = "CS10", Nombre = "ESCUELA NORMAL SUPERIOR GRAL MANUEL BELGRANO", Domicilio = "MITRE Nº 767", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS11", Codigo = "CS11", Nombre = "COLEGIO FRANCISCO DE GURRUCHAGA", Domicilio = "ZUVIRIA 290", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS12", Codigo = "CS12", Nombre = "COLEGIO MIGUEL RAGONE", Domicilio = "DEAN FUNES Nº 750", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CS13", Codigo = "CS13", Nombre = "SEMINARIO METROPOLITANO ", Domicilio = "MITRE 892 ", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_CENTRO" },

            new Establecimiento { Id = "CT01", Codigo = "CT01", Nombre = "DR. JOAQUIN CASTELLANOS ", Domicilio = "20 DE FEBRERO  131", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CT02", Codigo = "CT02", Nombre = "JUANA AZURDUY DE PADILLA", Domicilio = "GRAL LAVALLE 875", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CT03", Codigo = "CT03", Nombre = "GRAL MARTIN MIGUEL DE GUEMES", Domicilio = "CASEROS 1615", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CT04", Codigo = "CT04", Nombre = "ESCUELA TECNICA MARCELO LOTUFFO", Domicilio = "JJ.URQUIZA  529", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_CENTRO" },
            new Establecimiento { Id = "CT05", Codigo = "CT05", Nombre = "ALBERTO EINSTEIN", Domicilio = "TUCUMAN 505", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_CENTRO" },

            //zona ESTE
            new Establecimiento { Id = "E01", Codigo = "E01", Nombre = "CEFERINO NAMUNCURA", Domicilio = "CUBA 969 - Bº EL MILAGRO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E01BIS", Codigo = "E01BIS", Nombre = "ANEXO NUCLEO ED. Nº 7004-", Domicilio = "COMEDOR EL MILAGRO-CUBA 1045 -Bº EL MILAGRO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E02", Codigo = "E02", Nombre = "ARTURO OÑATIVIA", Domicilio = "R. LEVENE Y MIRANDA - Vª 20 DE JUNIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E02BIS", Codigo = "E02BIS", Nombre = "ANEXO NUCLEO ED. Nº 7004-", Domicilio = "R.LEVENE Y MIRANDA - vª 20 DE JUNIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E03", Codigo = "E03", Nombre = "BETANIA DEL SGDO. CORAZON", Domicilio = "FCO.VELEZ 318-VILLA 20 DE JUNIO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E04", Codigo = "E04", Nombre = "JOAQUIN CASTELLANOS", Domicilio = "LOS LIRIOS 190-VILLA LAS ROSAS", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E07", Codigo = "E07", Nombre = "FRAY LUIS BELTRAN", Domicilio = "AVDA. ARTIGAS 100- Bº CERAMICA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E07BIS", Codigo = "E07BIS", Nombre = "ANEXO NUCLEO ED. Nº 7004-", Domicilio = "AVDA ARTIGAS 100 - Bº CERAMICA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E08", Codigo = "E08", Nombre = "EJERCITO ARGENTINO", Domicilio = "AVDA. POMPILIO GUZ MAN Y ALDERETE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E08BIS", Codigo = "E08BIS", Nombre = "ANEXO NUCLEO ED. Nº 7004-", Domicilio = "AVDA. POMPILIO GUZ MAN Y ALDERETE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E10", Codigo = "E10", Nombre = "CAMPAÑA DEL DESIERTO", Domicilio = "AVDA. ASUNCION S/Nº Bº AUTODROMO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E10BIS", Codigo = "E10BIS", Nombre = "ANEXO NUCLEO ED. Nº 7004-", Domicilio = "AVDA. ASUNCION S/Nº Bº AUTODROMO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E11", Codigo = "E11", Nombre = "FRAY HONORATO PISTOIA", Domicilio = "ALCIDES JUAREZ TELLES 60- Bº MIRADOR", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "E12", Codigo = "E12", Nombre = "CORINA LONA", Domicilio = "FCO. DE GURRUCHAGA 50", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_ESTE" },

            new Establecimiento { Id = "EI01", Codigo = "EI01", Nombre = "CPO. INF. COM. 4TA.", Domicilio = "AV. POMPILO GUZMAN Nº 1850 - Vº MITRE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI04", Codigo = "EI04", Nombre = "MERENDERO AMOR Y FE", Domicilio = "J.M. GORRITI 1726 - Vª FLORESTA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI05", Codigo = "EI05", Nombre = "CATEQUESIS CEFERINO NAMUNCURA", Domicilio = "CUBA 969 - Bº EL MILAGRO- SABADO POR MEDIO-", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI12", Codigo = "EI12", Nombre = "MERENDERO AMANCAY", Domicilio = "AVDA CANADA 1672 - Bº EL MILAGRO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI16", Codigo = "EI16", Nombre = "MERENDERO NIÑOS DEL FUTURO", Domicilio = "MANZ. 5 LOTE 8 ASENT. LAS COLINAS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI18", Codigo = "EI18", Nombre = "CUERPO INFANTIL COM. 9na.", Domicilio = "GOMEZ RECIO 632 Bº PORTEZUELO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI19", Codigo = "EI19", Nombre = "CLUB ATLETICO MITRE", Domicilio = "AVDA DE LAS AMERICAS ESQ. VENEZUELA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI20", Codigo = "EI20", Nombre = "CENTRO VECINAL - Bº JARDIN", Domicilio = "EMILIO WIERNA Nº 1301 Bº EL JARDIN", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI21", Codigo = "EI21", Nombre = "MERENDERO BARRIO EL MILAGRO", Domicilio = "CUBA 1045 - BARRIO EL MILAGRO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI21Bis", Codigo = "EI21Bis", Nombre = "ANEXO NUCLEO ED. Nº 7004-", Domicilio = "CUBA 1045 - BARRIO EL MILAGRO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI22", Codigo = "EI22", Nombre = "MERENDERO ESCUELA DEPORTIVA Bº LAS COLINAS", Domicilio = "MANZ. 1 CASA 21 - BARRIO LAS COLINAS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI23", Codigo = "EI23", Nombre = "SUBCOMISARIA VILLA EL SOL", Domicilio = "AVDA. GURRUCHAGA 250", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI24", Codigo = "EI24", Nombre = "MERENDERO LUZ DE LOS NIÑOS EN ESPERANZA", Domicilio = "PJE. SOCOMPA Nº 1800", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI25", Codigo = "EI25", Nombre = "CPO.INF.POLICIA FEMENINA ", Domicilio = "OSCAR CABALEN Nº 530- Bº AUTODROMO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI26", Codigo = "EI26", Nombre = "DIRECCION CEMENTERIO PUBLICO", Domicilio = "CEMENTERIO DE LA SANTA CRUZ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI26BIS", Codigo = "EI26BIS", Nombre = "DIRECCION CEMENTERIO PUBLICO", Domicilio = "CEMENTERIO SAN ANTONIO DE PADUA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI27", Codigo = "EI27", Nombre = "MERENDERO BARRIO LA FAMA", Domicilio = "MANZ. 358- LOTE 17 - Bº LA FAMA - TEL.155130359", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "EI30", Codigo = "EI30", Nombre = "MERENDERO LOS PITUFUTOS", Domicilio = "LOS GLADIOLOS Nº 89 VILLA LAS ROSAS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_ESTE" },

            new Establecimiento { Id = "ES01", Codigo = "ES01", Nombre = "COLEGIO SECUNDARIO SARGENTO CABRAL", Domicilio = "CARMEN SALAS Nº 1349 - VILLA MITRE", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "ES02", Codigo = "ES02", Nombre = "COLEGIO SECUNDARIO Nº 5167 - MIGUEL RAGONE", Domicilio = "BARRIO AUTODROMO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "ES03", Codigo = "ES03", Nombre = "FRAY MAMERTO ESQUIU", Domicilio = "HIPOLITO IRIGOYEN 841", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "ES05", Codigo = "ES05", Nombre = "COLEGIO DEL PORTEZUELO", Domicilio = "HIPOLITO IRIGOYEN 841", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "ES06", Codigo = "ES06", Nombre = "COLEGIO BETANIA DEL SAGRADO CORAZON", Domicilio = "FCO VELEZ Nº 318- VILLA 20 DE JUNIO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "ES07", Codigo = "ES07", Nombre = "COLEGIO SECUNDARIO MARIA TERESA CADENA DE HESSLING", Domicilio = "FILIBERTO DE MENES Nº 536 - VILLA JUANITA.", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_ESTE" },

            new Establecimiento { Id = "ET01", Codigo = "ET01", Nombre = "ESCUELA Nº 3148 -OTTO KRAUSE", Domicilio = "JULIA ALDERETE 1450 - VILLA MITRE", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_ESTE" },
            new Establecimiento { Id = "ET02", Codigo = "ET02", Nombre = "CENTRO DE FORMACION PROFESIONAL", Domicilio = "JULIA ALDERETE 1450 - VILLA MITRE", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_ESTE" },

            //zona OESTE
            new Establecimiento { Id = "O01", Codigo = "O01", Nombre = "AML. GUILLERMO BROWN", Domicilio = "ISLAS MALVINAS Y TUCUMAN", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O01BIS", Codigo = "O01BIS", Nombre = "NUCLEO ED. Nº 7001", Domicilio = "ISLAS MALVINAS Y TUCUMAN", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O02", Codigo = "O02", Nombre = "ARMADA NACIONAL", Domicilio = "ORAN 1595 Vº LAS CHARTAS", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O03", Codigo = "O03", Nombre = "NTRA. SRA. DE LA CANDELARIA", Domicilio = "FINAL MOLDES - VILLA COSTANERA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O04", Codigo = "O04", Nombre = "MARIANO BOEDO", Domicilio = "CNEL VIDT Y CNEL MOLDES", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O06", Codigo = "O06", Nombre = "AMERICA LATINA", Domicilio = " CABO ALBERTO VIZGARRA Nº 659 Y MONGE ORTEGA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O07", Codigo = "O07", Nombre = "JUAN CARLOS DAVALOS", Domicilio = "CARLOS DEL CASTILLO 870 - VILLA PRIMAVERA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O07 BIS", Codigo = "O07 BIS", Nombre = "ANEXO NUCLEO ED. 7005", Domicilio = "CARLOS DEL CASTILLO 870 - VILLA PRIMAVERA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O09", Codigo = "O09", Nombre = "SAN JOSE", Domicilio = "USANDIVARAS 1396 - Bº SAN JOSE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O10", Codigo = "O10", Nombre = "SAGRADA FAMILIA", Domicilio = "MARIANO MORENO 1911", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O11", Codigo = "O11", Nombre = "EVARISTO PIÑON ARIAS", Domicilio = "EL CONDOR 3155 Bº SOLIS PIZARRO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O12", Codigo = "O12", Nombre = "SANTA LUCIA", Domicilio = " Bº SANTA LUCIA CALLE 6 - M 390", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O13", Codigo = "O13", Nombre = "MERCEDES LAVIN", Domicilio = "CARLOS CORTEZ Nº13- Bº EL PROGRESO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O14", Codigo = "O14", Nombre = "NTRA SRA. DE LA ASUNCION", Domicilio = "VILLA ASUNCION MZA 282 - L3", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O14BIS", Codigo = "O14BIS", Nombre = "ANEXO NUCLEO ED. 7005", Domicilio = "VILLA ASUNCION", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O15", Codigo = "O15", Nombre = "GUSTAVO CUCHI LEGUIZAMON", Domicilio = "Bº GUEMES -ARA PORTAVIONES 25 DE MAYO S/N", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O16", Codigo = "O16", Nombre = "ROBERTO ROMERO", Domicilio = "CALLE SAN GABRIEL S/Nº Bº ROBERTO ROMERO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O16bis", Codigo = "O16bis", Nombre = "ANEXO NUCLEO ED. 7005", Domicilio = "CALLE SAN GABRIEL S/Nº Bº ROBERTO ROMERO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O17", Codigo = "O17", Nombre = "PROF. OSCAR OÑATIVIA", Domicilio = "MANZ. 486 - Bº PALERMO I", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O17BIS", Codigo = "O17BIS", Nombre = "ANEXO NUCLEO ED. 7005", Domicilio = "MANZ. 486 - Bº PALERMO I", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O18", Codigo = "O18", Nombre = "NTRA. SRA. DEL CARMEN", Domicilio = "RIO PARANA S/Nº Vº PARQUE LAS VERTIENTES", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O18BIS", Codigo = "O18BIS", Nombre = "NUCLEO ED. Nº 7042 - LA CIENAGA", Domicilio = "DEJAR EN LA POLICIA DE LA CIENAGA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O19", Codigo = "O19", Nombre = "ANEXO NUCLEO ED. 7005", Domicilio = "DEJAR EN LA POLICIA DE LA CIENAGA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O20", Codigo = "O20", Nombre = "MARIANO CABEZON", Domicilio = "MENDOZA Y PJE. VICTORIA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O20BIS", Codigo = "O20BIS", Nombre = "NUCLEO ED. 7005", Domicilio = "MENDOZA Y PJE. VICTORIA", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O22", Codigo = "O22", Nombre = "BRIG. ALVAREZ Y ARENALES", Domicilio = "GRAL PAEZ 47", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O23", Codigo = "O23", Nombre = "SANTA EUFRASIA PELLETIER", Domicilio = "CNEL SUAREZ 317", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O23BIS", Codigo = "O23BIS", Nombre = "NUCLEO ED. Nº 7002", Domicilio = "CNEL SUAREZ 317", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O24", Codigo = "O24", Nombre = "MARTIN FIERRO", Domicilio = "PEDERNERA 1243 Vº LUJAN", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O28", Codigo = "O28", Nombre = "JUAN FCO. DE CASTRO", Domicilio = "POSTA DE YATASTO Y DR. ANZOATEGUI", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O29", Codigo = "O29", Nombre = "ESC. DIF. TOBAR GARCIA", Domicilio = "NECOCHEA Y BROWN", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O30", Codigo = "O30", Nombre = "ESC. TEC. DIF. Nº 27", Domicilio = "NECOCHEA Y BROWN- TURNO TARDE", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O31", Codigo = "O31", Nombre = "BARTOLOME MITRE", Domicilio = "OHIGGINS 1550", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O33", Codigo = "O33", Nombre = "REM.ESC. DE SAN MARTIN", Domicilio = "ENTRE RIOS 1551", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O35", Codigo = "O35", Nombre = "JARDIN INF. DIENTE FLOJO", Domicilio = "IBAZETA 885 - Bº 20 DE FEBRERO", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "O36", Codigo = "O36", Nombre = "PREJARDIN ATRAPASUEÑOS", Domicilio = "12 DE OCTUBRE 2061", TipoEstablecimientoId = "ID_ESCUELAS", ZonaId = "ID_OESTE" },

            new Establecimiento { Id = "OI01", Codigo = "OI01", Nombre = "A.P.A.D.I.", Domicilio = "BOLIVAR 605", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI02", Codigo = "OI02", Nombre = "NTRA SRA. DEL PILAR", Domicilio = "ANZOATEGUI 586", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI03", Codigo = "OI03", Nombre = "A.P.N.A.P.", Domicilio = "MENDOZA 1430", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI04", Codigo = "OI04", Nombre = "H.I.R.P.A.C.E", Domicilio = "SGO. DEL ESTERO 1951", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI06", Codigo = "OI06", Nombre = "CASITA DE BELEN", Domicilio = "MARIANO MORENO 1911", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI07", Codigo = "OI07", Nombre = "PARROQUIA SAN JOSE OBRERO", Domicilio = "JUAN LARREA 1161 - Bº SAN JOSE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI08", Codigo = "OI08", Nombre = "BIBLIOT. J.C. DAVALOS", Domicilio = "10 DE OCTUBRE 551", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI11", Codigo = "OI11", Nombre = "GUARDERIA NIÑOS DE BELEN", Domicilio = "ASUNCION ESQ. FATIMA - Vª ASUNCION", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI12", Codigo = "OI12", Nombre = "PROYECTO CUNIAVIHORTICOLA", Domicilio = "PJE. RAWSON Y MARIO DEL PIN- Bº STA. RITA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI14", Codigo = "OI14", Nombre = "CPO. INFANTIL COMISARIA 8VA.", Domicilio = "CLERICO S/Nº -Bº SANTA LUCIA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI16", Codigo = "OI16", Nombre = "FUNDACION  ANIDAR", Domicilio = "BOLIVAR 425 ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI17", Codigo = "OI17", Nombre = "MERENDERO EL PANALCITO", Domicilio = "CASA 58 - Bº SANTA RITA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI19", Codigo = "OI19", Nombre = "COMEDOR MI NINITO JESUS ", Domicilio = "LAS GAVIOTAS Y LAS GARZAS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI22", Codigo = "OI22", Nombre = "GUARDERIA COMEDOR LOS SALTEÑITOS", Domicilio = "PAVO REAL 1756 - Bº SOLIS PIZARRO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI24", Codigo = "OI24", Nombre = "POL. INF. COMISARIA 5TA.", Domicilio = "12 DE OCTUBRE  Nº 2230 - Vº LUJAN", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI25", Codigo = "OI25", Nombre = "IGLESIA SAN CAYETANO LA VERBENA", Domicilio = "AVDA. LOS PAJAROS 3078- FRENTE FRIG.BRUNETTI", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI26", Codigo = "OI26", Nombre = "MERENDERO LA RIBERA", Domicilio = "Bº RIBERA - LOTE 6 -Bº STA. LUCIA CALLE 14", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI29", Codigo = "OI29", Nombre = "PARROQUIA Bº SANTA LUCIA", Domicilio = "CALLE8-MED 234 - TEL4340881 - SABADOS UNICAMENTE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI31", Codigo = "OI31", Nombre = "PARR.NTRA. SRA DE LOS ANGELES", Domicilio = "SAN LUIS 1224 - TEL 4310428 - Fany Elena Gutierrez", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI34", Codigo = "OI34", Nombre = "GUARDERIA 4790- MUNDO FELIZ", Domicilio = "PJE.BALDOMERO CASTRO 1769", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI39", Codigo = "OI39", Nombre = "CLUB ABUELOS CRISTINO ZERPA", Domicilio = "SAN MARTIN Nº 2540", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI40", Codigo = "OI40", Nombre = "HOGAR DIVINO NIÑO", Domicilio = "RIVADAVIA 1640 - LUNES YOGUR - MIER. Y VIERNES LECHE", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI46", Codigo = "OI46", Nombre = "MERENDERO POR UN NIÑO FELIZ", Domicilio = "MANZ. 440C LOTE 13- Bº PALERMO II - TEL.4363230", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI55", Codigo = "OI55", Nombre = "MERENDERO MI NIÑO JESUS", Domicilio = "JUAN RAMON BOEDO Nº 968 - Vª PRIMAVERA -TEL.4344047", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI56", Codigo = "OI56", Nombre = "SUBCOMISARIA VILLA ASUNCION", Domicilio = "SENADOR MORON ESQ. AVDA LA PLATA - Bº OLIVOS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI60", Codigo = "OI60", Nombre = "CATEQ. PARR. SAN EXEQUIEL MORENO", Domicilio = "MANZ. 426B - LOTE 1- Bº PALERMO 1", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI61", Codigo = "OI61", Nombre = "CATEQ. PARR. NTRA. SRA DE LAS VICTORIAS ", Domicilio = "JOSE LEON CABEZON Y SANTA VICTORIA ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI65", Codigo = "OI65", Nombre = "BIBLIOTECA CASIMIRO COBOS", Domicilio = "POSTA DE YATASTO Nº 1489- SANTA LUCIA", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI66", Codigo = "OI66", Nombre = "MERENDERO SAN PABLO", Domicilio = "MANZ. 256 - LOTE 7 - Bº SAN PABLO - TEL. 4386009", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI67", Codigo = "OI67", Nombre = "PARROQUIA SAN PEDRO APOSTOL", Domicilio = "DE HUERGO 850 - VILLA PRIMAVERA - TEL. 4342040", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI68", Codigo = "OI68", Nombre = "CLUB CENTRAL NORTE", Domicilio = "ENTRE RIOS 1498", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI72", Codigo = "OI72", Nombre = "CATEQUESIS VICARIA CRISTO REY", Domicilio = "CARLOS GARDEL ESQ. MONGE ORTEGA - VILLA LOS SAUCES", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI73", Codigo = "OI73", Nombre = "CATEQUESIS  VICARIA SAN PABLO", Domicilio = "CARLOS GARDEL 628 - VILLA LOS SAUCES", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI74", Codigo = "OI74", Nombre = "VICARIA VIRGEN DE LAS LAGRIMAS ", Domicilio = "AVDA DI PASCUO S/Nº - 155013000- ANA SOL- A PARTIR HS. 17.00", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI75", Codigo = "OI75", Nombre = "MERENDERO DULCE ESPERANZA", Domicilio = "MANZ. 180 - LOTE 3 -BARRIO ROBERTO ROMERO", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI76", Codigo = "OI76", Nombre = "FUNDACION ENCUENTRO ", Domicilio = "ALVEAR 560 (llevar insumos de 9 a 12 o 14hs) LACTEOS LUNES UNIC", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI77", Codigo = "OI77", Nombre = "BIBLIOTECA POPULAR Bº -PALERMO I", Domicilio = "MANZ. 426 C - LOTE 13 - Bº PALERMO I - TEL. 4361926", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI79", Codigo = "OI79", Nombre = "MERENDERO CARITA FELIZ", Domicilio = "MAN.459 A-LOTE 5-B° ALTO LA VIÑA-SRA. BEATRIZ JESUS-155192496", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI105", Codigo = "OI105", Nombre = "EXPLORADORAS ARG.MA.AUXILIADORA", Domicilio = "BOLIVAR 270", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI110", Codigo = "OI110", Nombre = "CLUB PELLEGRINI ", Domicilio = "Bº LAS MAGDALENAS MNA. 124B CASA 7 ", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OI111", Codigo = "OI111", Nombre = "ESC. DE BOX CIRILO GIL", Domicilio = "REPUBLICA DE SIRIA Nº 49 Bº CAMPO CASEROS", TipoEstablecimientoId = "ID_INSTITUCIONES", ZonaId = "ID_OESTE" },

            new Establecimiento { Id = "OS01", Codigo = "OS01", Nombre = "COLEGIO SECUNDARIO PROF. NESTOR PALACIOS", Domicilio = "CALLE 13 Y 10 - Bº SANTA LUCIA.", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS02", Codigo = "OS02", Nombre = "COLEGIO SECUNDARIO JUAN CALCHAQUI", Domicilio = "10 DE OCTUBRE Nº 551", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS03", Codigo = "OS03", Nombre = "ESCUELA DE COMERCIO 25 DE MAYO", Domicilio = "IBAZETA Nº 690", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS04", Codigo = "OS04", Nombre = "COLEGIO SECUNDARIO SAN JOSE DE CALAZANZ", Domicilio = "USANDIVARAS Y 20 DE JUNIO- BARRIO SAN JOSE", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS05", Codigo = "OS05", Nombre = "COLEGIO SECUNDARIO DR. RAUL ALFONSIN", Domicilio = "MENSOZA Y PJE. SANTA VICTORIA - VESPERTINO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS06", Codigo = "OS06", Nombre = "ESC. DE COM. 5084 EX. COMB DE MALVINAS", Domicilio = "CNEL. MOLDES Y CNEL. VIDT. - TURNO VESPERTINO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS07", Codigo = "OS07", Nombre = "ESCUELA DE COMERCIO 5075", Domicilio = "12 DE OCTUBRE Nº 654", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS08", Codigo = "OS08", Nombre = "COLEGIO SEC. SAGRADA FAMILIA", Domicilio = "MARIANO MORENO 1911", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS09", Codigo = "OS09", Nombre = "COLEGIO SEC. EVARISTO PIÑON ARIAS", Domicilio = "EL CONDOR 3150", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS10", Codigo = "OS10", Nombre = "BACHILLERATO  INTEGRAL RAUL SCALABRINI ORTIZ", Domicilio = "SAN MARTIN 1800", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS10 BIS", Codigo = "OS10 BIS", Nombre = "ANEXO POLO REINGRESO", Domicilio = "SAN MARTIN 1800", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS11", Codigo = "OS11", Nombre = "POLO REINGRESO COL. SEC. Nº 5159 Bº PALERMO", Domicilio = "AVDA PORTAVIONES S/Nº -POLO REINGRESO", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OS12", Codigo = "OS12", Nombre = "COLEGIO SEC. Nº 5159- Bº PALERMO I", Domicilio = "AVDA HIPODROMO DE SAN ISIDRO 750", TipoEstablecimientoId = "ID_SECUNDARIOS", ZonaId = "ID_OESTE" },

            new Establecimiento { Id = "OT01", Codigo = "OT01", Nombre = "ESCUELA Nº 3105", Domicilio = "CARLOS DEL CASTILLO 870 - VILLA PRIMAVERA", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OT02", Codigo = "OT02", Nombre = "REPUBLICA DE LA INDIA", Domicilio = "ALMIRANTE BROWN S/Nº", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OT03", Codigo = "OT03", Nombre = "MARTINA SILVA DE GURRUCHAGA", Domicilio = "AVDA ENTRE RIOS Nº 1895", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OT04", Codigo = "OT04", Nombre = "DR. FCO. DE GURRUCHAGA", Domicilio = "12 DE OCTUBRE E IBAZETA", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_OESTE" },
            new Establecimiento { Id = "OT05", Codigo = "OT05", Nombre = "DR. JULIO MERA FIGUEROA", Domicilio = "MANZ. A - Bº JESUS MARIA", TipoEstablecimientoId = "ID_TECNICAS", ZonaId = "ID_OESTE" }
            );
        }
    }
}
